name: spidev
version: 0.0.0.0
synopsis: Interface with spidev on Linux
github: vkleen/relayctl
category: Utility

license: BSD-3-Clause
author: Viktor Kleen
maintainer: viktor@kleen.org
copyright: 2020 Viktor Kleen

ghc-options:
  - -Wall
  - -Wincomplete-uni-patterns
  - -Wincomplete-record-updates
  - -Wcompat
  - -Widentities
  - -Wredundant-constraints
  - -fhide-source-paths
  - -Wmissing-export-lists
  - -Wno-missing-methods
  - -Wno-type-defaults
default-extensions:
  - AllowAmbiguousTypes
  - ApplicativeDo
  - BlockArguments
  - DataKinds
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - DerivingVia
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GADTs
  - InstanceSigs
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NoMonomorphismRestriction
  - NoStarIsType
  - OverloadedLabels
  - OverloadedStrings
  - PolyKinds
  - QuasiQuotes
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators
  - UndecidableInstances

dependencies:
  - name: base
    mixin:
      - hiding (Prelude)
  - name: relude
    mixin:
      - (Relude as Prelude)
      - (Relude.Unsafe as Unsafe)

library:
  source-dirs: src

  dependencies:
    - bytestring
    - finite-typelits
    - inline-c
    - unix
    - vector
    - vector-sized
